fieldLayouts:
  ee5f7ff2-062f-494b-a8fc-ed8cb12eecfd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a02f706-2b60-4ec1-9a77-96a5d82a53b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a520d1b-b605-44aa-8200-d7784b974f5b # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19c0af6a-f83f-4a70-acbf-7d665a802d29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dcc6c87b-20a8-4fc8-847d-51fd4e86314d # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 995e02b1-8b8b-45df-b690-5c9b38be1961
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79539452-eba4-496b-882a-05e6b85a8053
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 587357c8-2262-4666-9705-2f0b84385392 # Destinations
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
