columnSuffix: null
contentColumnType: string
fieldGroup: 31006d4c-2f40-498c-9a4c-69cff4fd4279 # Common
handle: tags
instructions: 'Be sure to order the tags appropriately as the first tag gets the most weight and the last tag gets the least weight.'
name: Tags
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 5
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add a tag'
  showSiteMenu: true
  sources:
    - 'section:7ecb6c5b-40bf-4fc0-a015-5367a2e9d85b' # Tags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
